server:
    port: 8080
    address: 127.0.0.1

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/bankDataBase
        username: postgres
        password: MinDBqw3rTyAd
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        database: postgresql
        show-sql: true
