server:
    port: 8080
    address: 127.0.0.1
spring:
    flyway:
        enabled: false
        locations: classpath:db/migration
        baseline-on-migrate: true
        connectRetries: 3
        encoding: UTF-8
        clean-disabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/bankDataBase
        username: postgres
        password: MinDBqw3rTyAd
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        show-sql: true

